// translator.js

// Словарь переводов
const translations = {
    "ru": {
        // Общие ключи для всех страниц
        "page_title_index": "Персонализированные Юридические Услуги | Главная",
        "page_title_services": "Услуги | Персонализированные Юридические Услуги",
        "page_title_about": "О компании | Персонализированные Юридические Услуги",
        "page_title_prices": "Цены | Персонализированные Юридические Услуги",
        "logo": "Юридическая Компания",
        "nav_home": "Главная",
        "nav_about": "О компании",
        "nav_services": "Услуги",
        "nav_prices": "Цены",
        "nav_blog": "Блог",
        "nav_contact": "Контакты",
        "nav_login": "Личный кабинет",
        "theme_toggle": "Тёмная тема",
        "language_toggle_ru": "RU",
        "language_toggle_en": "EN",
        "hero_title": "Персонализированные Юридические Услуги",
        "hero_subtitle": "Мы предоставляем качественные юридические решения, адаптированные под ваши нужды.",
        "hero_button": "Наши услуги",
        "about_title": "О нашей компании",
        "about_description": "Наша юридическая компания обладает многолетним опытом в предоставлении высококачественных юридических услуг для корпоративных клиентов. Мы стремимся обеспечить наших клиентов персонализированными решениями, которые соответствуют их уникальным потребностям.",
        "services_title": "Наши услуги",
        "about_section_title": "О нашей компании",
        "about_section_description": "Наша юридическая компания была основана в 2010 году с целью предоставления высококачественных юридических услуг для корпоративных клиентов. За годы работы мы зарекомендировали себя как надежного партнера, предлагающего индивидуальные решения для каждого клиента.",
        "mission_title": "Наша миссия",
        "mission_description": "Мы стремимся обеспечивать наших клиентов экспертной юридической поддержкой, способствуя успешному развитию их бизнеса и защите их интересов. Наша миссия — быть лидерами в области корпоративного права, предоставляя инновационные и эффективные решения.",
        "team_title": "Наша команда",
        "team_member1_alt": "Иван Иванов",
        "team_member1_name": "Иван Иванов",
        "team_member1_position": "Генеральный директор",
        "team_member2_alt": "Мария Петрова",
        "team_member2_name": "Мария Петрова",
        "team_member2_position": "Главный юрисконсульт",
        "team_member3_alt": "Алексей Смирнов",
        "team_member3_name": "Алексей Смирнов",
        "team_member3_position": "Менеджер по работе с клиентами",
        "values_title": "Наши ценности",
        "value_professionalism": "Профессионализм и экспертиза",
        "value_individual_approach": "Индивидуальный подход",
        "value_responsibility": "Ответственность и надежность",
        "value_innovation": "Инновации и развитие",
        "footer_text": "&copy; 2024 Юридическая Компания. Все права защищены.",

        // Ключи для страницы услуг
        "services_section_title": "Наши услуги",
        "services_section_description": "Мы предлагаем широкий спектр юридических услуг, направленных на поддержку и развитие вашего бизнеса.",
        "service_corporate_consultations_title": "Консультации по корпоративному праву",
        "service_corporate_consultations_desc": "Профессиональные консультации по вопросам корпоративного управления и структуры.",
        "service_contracts_title": "Разработка и анализ договоров",
        "service_contracts_desc": "Создание и проверка юридически грамотных договоров, защищающих ваши интересы.",
        "service_litigation_title": "Представительство в суде",
        "service_litigation_desc": "Эффективное представление ваших интересов в судебных инстанциях.",
        "service_tax_consulting_title": "Налоговое консультирование",
        "service_tax_consulting_desc": "Оптимизация налоговой нагрузки и соблюдение всех налоговых требований.",

        // Ключи для страницы цен
        "pricing_section_title": "Наши цены",
        "pricing_section_description": "Мы предлагаем прозрачную и конкурентоспособную ценовую политику, адаптированную под потребности каждого клиента.",
        "pricing_card_basic": "Тарифный план Базовый",
        "pricing_plan_basic_title": "Базовый",
        "pricing_plan_basic_price": "5 000",
        "pricing_plan_basic_currency": "₽/месяц",
        "pricing_plan_basic_feature1": "Консультации до 2 часов",
        "pricing_plan_basic_feature2": "Разработка стандартных договоров",
        "pricing_plan_basic_feature3": "Доступ к онлайн-ресурсам",
        "pricing_plan_basic_button": "Выбрать",

        "pricing_card_standard": "Тарифный план Стандартный",
        "pricing_plan_standard_title": "Стандартный",
        "pricing_plan_standard_price": "10 000",
        "pricing_plan_standard_currency": "₽/месяц",
        "pricing_plan_standard_feature1": "Консультации до 5 часов",
        "pricing_plan_standard_feature2": "Разработка и анализ договоров",
        "pricing_plan_standard_feature3": "Представительство в суде",
        "pricing_plan_standard_feature4": "Налоговое консультирование",
        "pricing_plan_standard_button": "Выбрать",

        "pricing_card_premium": "Тарифный план Премиум",
        "pricing_plan_premium_title": "Премиум",
        "pricing_plan_premium_price": "20 000",
        "pricing_plan_premium_currency": "₽/месяц",
        "pricing_plan_premium_feature1": "Неограниченные консультации",
        "pricing_plan_premium_feature2": "Комплексное юридическое сопровождение",
        "pricing_plan_premium_feature3": "Индивидуальные решения для бизнеса",
        "pricing_plan_premium_feature4": "Приоритетная поддержка",
        "pricing_plan_premium_button": "Выбрать",

        // Секция Блога
        "blog_post1_title": "Преимущества использования юридических услуг для вашего бизнеса",
        "blog_post1_meta": "Автор: Иван Иванов | Дата: 20.04.2024 | Категория: Корпоративное право",
        "blog_post1_paragraph1": "В современном бизнесе юридическая поддержка играет ключевую роль в обеспечении стабильности и роста компании. В этой статье мы рассмотрим основные преимущества использования профессиональных юридических услуг для вашего бизнеса.",
        "blog_post1_subtitle1": "1. Правовая безопасность",
        "blog_post1_paragraph2": "Юридические услуги помогают обеспечить соблюдение всех законодательных требований, что минимизирует риски штрафов и санкций. Профессиональный юрист всегда в курсе последних изменений в законодательстве и может своевременно информировать вас о необходимых действиях.",
        "blog_post1_subtitle2": "2. Разработка и анализ договоров",
        "blog_post1_paragraph3": "Качественно составленные договоры защищают интересы вашей компании и предотвращают возможные споры с партнерами и клиентами. Юридическая помощь в этом процессе гарантирует, что все условия договора четко прописаны и соответствуют вашим потребностям.",
        "blog_post1_subtitle3": "3. Представительство в суде",
        "blog_post1_paragraph4": "В случае судебных разбирательств наличие опытного юриста, который будет представлять интересы вашей компании, существенно повышает шансы на благоприятный исход дела. Юридическая поддержка в суде обеспечивает профессиональное ведение процесса и защиту ваших прав.",
        "blog_post1_subtitle4": "4. Стратегическое планирование",
        "blog_post1_paragraph5": "Юристы могут помочь в разработке стратегических планов развития бизнеса, учитывая правовые аспекты. Это включает в себя выбор оптимальной юридической формы компании, регистрацию интеллектуальной собственности и другие важные вопросы.",
        "blog_post1_subtitle5": "5. Экономия времени и ресурсов",
        "blog_post1_paragraph6": "Ведение юридических дел самостоятельно может быть временно затратным и требовать значительных ресурсов. Профессиональные юридические услуги позволяют сосредоточиться на основных аспектах бизнеса, доверив правовые вопросы специалистам.",
        "blog_post1_paragraph7": "В заключение, использование юридических услуг предоставляет вашему бизнесу множество преимуществ, от обеспечения правовой безопасности до стратегического планирования и экономии ресурсов. Инвестирование в профессиональную юридическую поддержку является важным шагом на пути к успешному развитию вашего бизнеса.",

        // Комментарии
        "comments_section_title": "Комментарии",
        "comments_form_name_label": "Имя:",
        "comments_form_name_placeholder": "Ваше имя",
        "comments_form_comment_label": "Комментарий:",
        "comments_form_comment_placeholder": "Ваш комментарий",
        "comments_form_submit_button": "Отправить",

        // Боковая панель (Sidebar)
        "sidebar_search_title": "Поиск",
        "sidebar_search_placeholder": "Поиск статей...",
        "sidebar_search_button": "Найти",
        "sidebar_categories_title": "Категории",
        "sidebar_category_corporate": "Корпоративное право",
        "sidebar_category_tax": "Налоговое право",
        "sidebar_category_contracts": "Договорное право",
        "sidebar_category_labor": "Трудовое право",
        "sidebar_category_international": "Международное право",
        "sidebar_recent_posts_title": "Последние посты",
        "sidebar_recent_post1_image_alt": "Недавняя статья 1",
        "sidebar_recent_post1_title": "Преимущества использования юридических услуг для вашего бизнеса",
        "sidebar_recent_post2_image_alt": "Недавняя статья 2",
        "sidebar_recent_post2_title": "Как выбрать правильного юриста для вашего дела",
        "sidebar_recent_post3_image_alt": "Недавняя статья 3",
        "sidebar_recent_post3_title": "Новые изменения в налоговом законодательстве 2024 года",
        "sidebar_archive_title": "Архив",
        "sidebar_archive_april": "Апрель 2024",
        "sidebar_archive_march": "Март 2024",
        "sidebar_archive_february": "Февраль 2024",
        "sidebar_archive_january": "Январь 2024",

        "title": "Персонализированные Юридические Услуги",
        "logo": "Юридическая Компания",
        "nav_home": "Главная",
        "nav_about": "О компании",
        "nav_services": "Услуги",
        "nav_prices": "Цены",
        "nav_blog": "Блог",
        "nav_contact": "Контакты",
        "nav_login": "Личный кабинет",
        "theme_toggle": "Тёмная тема",
        "hero_title": "Персонализированные Юридические Услуги",
        "hero_subtitle": "Мы предоставляем качественные юридические решения, адаптированные под ваши нужды.",
        "hero_button": "Наши услуги",
        "about_title": "О нашей компании",
        "about_description": "Наша юридическая компания обладает многолетним опытом в предоставлении высококачественных юридических услуг для корпоративных клиентов. Мы стремимся обеспечить наших клиентов персонализированными решениями, которые соответствуют их уникальным потребностям.",
        "services_title": "Наши услуги",
        "service_consultations": "Консультации",
        "service_consultations_desc": "Профессиональные юридические консультации по различным вопросам.",
        "service_contracts": "Договорное право",
        "service_contracts_desc": "Разработка и анализ договоров, защита ваших интересов.",
        "service_litigation": "Представительство в суде",
        "service_litigation_desc": "Эффективное представление ваших интересов в судебных инстанциях.",
        "service_corporate": "Корпоративное право",
        "service_corporate_desc": "Юридическое сопровождение бизнеса на всех этапах.",
        "advantages_title": "Почему выбирают нас",
        "advantage_experienced": "Опытная команда профессионалов",
        "advantage_individual": "Индивидуальный подход к каждому клиенту",
        "advantage_responsibility": "Высокий уровень ответственности и этики",
        "advantage_comprehensive": "Комплексные решения для бизнеса",
        "footer_text": "&copy; 2024 Юридическая Компания. Все права защищены.",

        "page_title_blog_post1": "Преимущества использования юридических услуг для вашего бизнеса | Блог",
        "blog_post1_title": "Преимущества использования юридических услуг для вашего бизнеса",
        "blog_post1_meta": "Автор: Иван Иванов | Дата: 20.04.2024 | Категория: Корпоративное право",
        "blog_post1_image_alt": "Преимущества юридических услуг",
        "blog_post1_paragraph1": "В современном бизнесе юридическая поддержка играет ключевую роль в обеспечении стабильности и роста компании. В этой статье мы рассмотрим основные преимущества использования профессиональных юридических услуг для вашего бизнеса.",
        "blog_post1_subtitle1": "1. Правовая безопасность",
        "blog_post1_paragraph2": "Юридические услуги помогают обеспечить соблюдение всех законодательных требований, что минимизирует риски штрафов и санкций. Профессиональный юрист всегда в курсе последних изменений в законодательстве и может своевременно информировать вас о необходимых действиях.",
        "blog_post1_subtitle2": "2. Разработка и анализ договоров",
        "blog_post1_paragraph3": "Качественно составленные договоры защищают интересы вашей компании и предотвращают возможные споры с партнерами и клиентами. Юридическая помощь в этом процессе гарантирует, что все условия договора четко прописаны и соответствуют вашим потребностям.",
        "blog_post1_subtitle3": "3. Представительство в суде",
        "blog_post1_paragraph4": "В случае судебных разбирательств наличие опытного юриста, который будет представлять интересы вашей компании, существенно повышает шансы на благоприятный исход дела. Юридическая поддержка в суде обеспечивает профессиональное ведение процесса и защиту ваших прав.",
        "blog_post1_subtitle4": "4. Стратегическое планирование",
        "blog_post1_paragraph5": "Юристы могут помочь в разработке стратегических планов развития бизнеса, учитывая правовые аспекты. Это включает в себя выбор оптимальной юридической формы компании, регистрацию интеллектуальной собственности и другие важные вопросы.",
        "blog_post1_subtitle5": "5. Экономия времени и ресурсов",
        "blog_post1_paragraph6": "Ведение юридических дел самостоятельно может быть временно затратным и требовать значительных ресурсов. Профессиональные юридические услуги позволяют сосредоточиться на основных аспектах бизнеса, доверив правовые вопросы специалистам.",
        "blog_post1_paragraph7": "В заключение, использование юридических услуг предоставляет вашему бизнесу множество преимуществ, от обеспечения правовой безопасности до стратегического планирования и экономии ресурсов. Инвестирование в профессиональную юридическую поддержку является важным шагом на пути к успешному развитию вашего бизнеса.",
        "comments_section_title": "Комментарии",
        "comments_form_name_label": "Имя:",
        "comments_form_name_placeholder": "Ваше имя",
        "comments_form_comment_label": "Комментарий:",
        "comments_form_comment_placeholder": "Ваш комментарий",
        "comments_form_submit_button": "Отправить",
        "footer_facebook_alt": "Facebook",
        "footer_twitter_alt": "Twitter",
        "footer_linkedin_alt": "LinkedIn",

        "page_title_contact": "Контакты | Персонализированные Юридические Услуги",
        "logo": "Юридическая Компания",
        "nav_home": "Главная",
        "nav_about": "О компании",
        "nav_services": "Услуги",
        "nav_prices": "Цены",
        "nav_blog": "Блог",
        "nav_contact": "Контакты",
        "nav_login": "Личный кабинет",
        "theme_toggle": "Тёмная тема",
        "language_toggle_ru": "RU",
        "language_toggle_en": "EN",
        "contact_hero_title": "Свяжитесь с нами",
        "contact_hero_description": "Мы всегда готовы помочь вам с вашими юридическими вопросами. Заполните форму ниже или свяжитесь с нами по указанным контактам.",
        "contact_form_title": "Форма обратной связи",
        "contact_form_name_label": "Имя:",
        "contact_form_name_placeholder": "Ваше имя",
        "contact_form_email_label": "Email:",
        "contact_form_email_placeholder": "Ваш email",
        "contact_form_subject_label": "Тема:",
        "contact_form_subject_placeholder": "Тема сообщения",
        "contact_form_message_label": "Сообщение:",
        "contact_form_message_placeholder": "Ваше сообщение",
        "contact_form_submit_button": "Отправить",
        "contact_info_title": "Наши контакты",
        "contact_phone_alt": "Телефон",
        "contact_phone_number": "+7 (123) 456-78-90",
        "contact_email_alt": "Email",
        "contact_email_address": "info@legalcompany.ru",
        "contact_address_alt": "Адрес",
        "contact_address": "г. Москва, ул. Примерная, д. 1, офис 101",
        "contact_work_hours_alt": "Время работы",
        "contact_work_hours": "Пн-Пт: 9:00 - 18:00",
        "social_facebook_alt": "Facebook",
        "social_twitter_alt": "Twitter",
        "social_linkedin_alt": "LinkedIn",
        "contact_map_title": "Наше местоположение",
        "contact_map_iframe_title": "Карта местоположения Юридической Компании",
        "notification_success": "Ваше сообщение успешно отправлено! Мы свяжемся с вами в ближайшее время.",
        "footer_text": "&copy; 2024 Юридическая Компания. Все права защищены.",

        "page_title_register": "Регистрация | Личный кабинет",
        "logo": "Юридическая Компания",
        "nav_home": "Главная",
        "nav_about": "О компании",
        "nav_services": "Услуги",
        "nav_prices": "Цены",
        "nav_blog": "Блог",
        "nav_contact": "Контакты",
        "nav_login": "Личный кабинет",
        "nav_register": "Регистрация",
        "theme_toggle": "Тёмная тема",
        "language_toggle_ru": "RU",
        "language_toggle_en": "EN",
        "register_title": "Регистрация",
        "register_form_name_label": "Имя:",
        "register_form_name_placeholder": "Ваше имя",
        "register_form_email_label": "Email:",
        "register_form_email_placeholder": "Ваш email",
        "register_form_password_label": "Пароль:",
        "register_form_password_placeholder": "Ваш пароль",
        "register_form_confirm_password_label": "Подтверждение пароля:",
        "register_form_confirm_password_placeholder": "Подтвердите пароль",
        "register_form_submit_button": "Зарегистрироваться",
        "register_form_login_prompt": "Уже есть аккаунт? <a href=\"login.html\" data-i18n=\"register_form_login_link\">Войдите</a>.",
        "register_form_login_link": "Войдите",
        "notification_register_success": "Ваш аккаунт успешно создан! Добро пожаловать.",

        // Ключи для страницы login.html
        "page_title_login": "Вход | Личный кабинет",
        "login_title": "Вход",
        "login_form_email_label": "Email:",
        "login_form_email_placeholder": "Ваш email",
        "login_form_password_label": "Пароль:",
        "login_form_password_placeholder": "Ваш пароль",
        "login_form_submit_button": "Войти",
        "login_form_register_prompt": "Еще нет аккаунта? <a href=\"register.html\" data-i18n=\"login_form_register_link\">Зарегистрируйтесь</a>.",
        "login_form_register_link": "Зарегистрируйтесь",
        "notification_login_success": "Вы успешно вошли в систему! Добро пожаловать.",
        "page_title_dashboard": "Личный кабинет | Юридическая Компания",
        "logo": "Юридическая Компания",
        "nav_home": "Главная",
        "nav_about": "О компании",
        "nav_services": "Услуги",
        "nav_prices": "Цены",
        "nav_blog": "Блог",
        "nav_contact": "Контакты",
        "nav_logout": "Выйти",
        "theme_toggle": "Тёмная тема",
        "language_toggle_ru": "RU",
        "language_toggle_en": "EN",
        "dashboard_welcome": "Добро пожаловать, <span id=\"userName\">Пользователь</span>!",
        "dashboard_your_data": "Ваши данные",
        "dashboard_name_label": "Имя:",
        "dashboard_email_label": "Email:",
        "dashboard_actions": "Действия",
        "dashboard_contact_us_button": "Связаться с нами",
        "offers_title": "Персонализированные Предложения",
        "social_facebook_alt": "Facebook",
        "social_twitter_alt": "Twitter",
        "social_linkedin_alt": "LinkedIn",
        "contact_map_iframe_title": "Карта местоположения Юридической Компании",
        "notification_logout_success": "Вы успешно вышли из системы."
    },
    "en": {
        "page_title_dashboard": "Dashboard | Legal Company",
        "logo": "Legal Company",
        "nav_home": "Home",
        "nav_about": "About Us",
        "nav_services": "Services",
        "nav_prices": "Prices",
        "nav_blog": "Blog",
        "nav_contact": "Contact",
        "nav_logout": "Logout",
        "theme_toggle": "Light Theme",
        "language_toggle_ru": "RU",
        "language_toggle_en": "EN",
        "dashboard_welcome": "Welcome, <span id=\"userName\">User</span>!",
        "dashboard_your_data": "Your Data",
        "dashboard_name_label": "Name:",
        "dashboard_email_label": "Email:",
        "dashboard_actions": "Actions",
        "dashboard_contact_us_button": "Contact Us",
        "offers_title": "Personalized Offers",
        "social_facebook_alt": "Facebook",
        "social_twitter_alt": "Twitter",
        "social_linkedin_alt": "LinkedIn",
        "contact_map_iframe_title": "Map of Legal Company's Location",
        "notification_logout_success": "You have successfully logged out.",
        "page_title_register": "Registration | Dashboard",
        "logo": "Legal Company",
        "nav_home": "Home",
        "nav_about": "About Us",
        "nav_services": "Services",
        "nav_prices": "Prices",
        "nav_blog": "Blog",
        "nav_contact": "Contact",
        "nav_login": "Dashboard",
        "nav_register": "Register",
        "theme_toggle": "Light Theme",
        "language_toggle_ru": "RU",
        "language_toggle_en": "EN",
        "register_title": "Registration",
        "register_form_name_label": "Name:",
        "register_form_name_placeholder": "Your Name",
        "register_form_email_label": "Email:",
        "register_form_email_placeholder": "Your Email",
        "register_form_password_label": "Password:",
        "register_form_password_placeholder": "Your Password",
        "register_form_confirm_password_label": "Confirm Password:",
        "register_form_confirm_password_placeholder": "Confirm Password",
        "register_form_submit_button": "Register",
        "register_form_login_prompt": "Already have an account? <a href=\"login.html\" data-i18n=\"register_form_login_link\">Login</a>.",
        "register_form_login_link": "Login",
        "notification_register_success": "Your account has been successfully created! Welcome.",

        // Ключи для страницы login.html
        "page_title_login": "Login | Dashboard",
        "login_title": "Login",
        "login_form_email_label": "Email:",
        "login_form_email_placeholder": "Your Email",
        "login_form_password_label": "Password:",
        "login_form_password_placeholder": "Your Password",
        "login_form_submit_button": "Login",
        "login_form_register_prompt": "Don't have an account? <a href=\"register.html\" data-i18n=\"login_form_register_link\">Register</a>.",
        "login_form_register_link": "Register",
        "notification_login_success": "You have successfully logged in! Welcome.",

        "page_title_contact": "Contact Us | Personalized Legal Services",
        "logo": "Legal Company",
        "nav_home": "Home",
        "nav_about": "About Us",
        "nav_services": "Services",
        "nav_prices": "Prices",
        "nav_blog": "Blog",
        "nav_contact": "Contact",
        "nav_login": "Dashboard",
        "theme_toggle": "Light Theme",
        "language_toggle_ru": "RU",
        "language_toggle_en": "EN",
        "contact_hero_title": "Get in Touch",
        "contact_hero_description": "We are always ready to assist you with your legal questions. Fill out the form below or contact us using the provided information.",
        "contact_form_title": "Feedback Form",
        "contact_form_name_label": "Name:",
        "contact_form_name_placeholder": "Your Name",
        "contact_form_email_label": "Email:",
        "contact_form_email_placeholder": "Your Email",
        "contact_form_subject_label": "Subject:",
        "contact_form_subject_placeholder": "Subject of Message",
        "contact_form_message_label": "Message:",
        "contact_form_message_placeholder": "Your Message",
        "contact_form_submit_button": "Submit",
        "contact_info_title": "Our Contacts",
        "contact_phone_alt": "Phone",
        "contact_phone_number": "+7 (123) 456-78-90",
        "contact_email_alt": "Email",
        "contact_email_address": "info@legalcompany.ru",
        "contact_address_alt": "Address",
        "contact_address": "Moscow, Example Street, Building 1, Office 101",
        "contact_work_hours_alt": "Working Hours",
        "contact_work_hours": "Mon-Fri: 9:00 AM - 6:00 PM",
        "social_facebook_alt": "Facebook",
        "social_twitter_alt": "Twitter",
        "social_linkedin_alt": "LinkedIn",
        "contact_map_title": "Our Location",
        "contact_map_iframe_title": "Map of Legal Company's Location",
        "notification_success": "Your message has been successfully sent! We will contact you shortly.",
        "footer_text": "&copy; 2024 Legal Company. All rights reserved.",
        "page_title_blog_post1": "Benefits of Using Legal Services for Your Business | Blog",
        "blog_post1_title": "Benefits of Using Legal Services for Your Business",
        "blog_post1_meta": "Author: Ivan Ivanov | Date: 20.04.2024 | Category: Corporate Law",
        "blog_post1_image_alt": "Benefits of Legal Services",
        "blog_post1_paragraph1": "In today's business world, legal support plays a key role in ensuring the stability and growth of a company. In this article, we will explore the main benefits of using professional legal services for your business.",
        "blog_post1_subtitle1": "1. Legal Security",
        "blog_post1_paragraph2": "Legal services help ensure compliance with all legislative requirements, minimizing the risks of fines and sanctions. A professional lawyer is always up-to-date with the latest changes in legislation and can promptly inform you about necessary actions.",
        "blog_post1_subtitle2": "2. Contract Development and Analysis",
        "blog_post1_paragraph3": "Well-drafted contracts protect your company's interests and prevent potential disputes with partners and clients. Legal assistance in this process ensures that all contract terms are clearly written and tailored to your needs.",
        "blog_post1_subtitle3": "3. Court Representation",
        "blog_post1_paragraph4": "In the event of legal disputes, having an experienced lawyer representing your company's interests significantly increases the chances of a favorable outcome. Legal support in court ensures professional handling of the process and protection of your rights.",
        "blog_post1_subtitle4": "4. Strategic Planning",
        "blog_post1_paragraph5": "Lawyers can assist in developing strategic business growth plans, considering legal aspects. This includes choosing the optimal legal form of the company, registering intellectual property, and other important matters.",
        "blog_post1_subtitle5": "5. Time and Resource Savings",
        "blog_post1_paragraph6": "Handling legal matters independently can be time-consuming and require significant resources. Professional legal services allow you to focus on the core aspects of your business, entrusting legal issues to specialists.",
        "blog_post1_paragraph7": "In conclusion, using legal services offers your business numerous benefits, from ensuring legal security to strategic planning and resource savings. Investing in professional legal support is an important step towards the successful development of your business.",
        "comments_section_title": "Comments",
        "comments_form_name_label": "Name:",
        "comments_form_name_placeholder": "Your Name",
        "comments_form_comment_label": "Comment:",
        "comments_form_comment_placeholder": "Your Comment",
        "comments_form_submit_button": "Submit",
        "footer_facebook_alt": "Facebook",
        "footer_twitter_alt": "Twitter",
        "footer_linkedin_alt": "LinkedIn",

        // Общие ключи для всех страниц
        "page_title_index": "Personalized Legal Services | Home",
        "page_title_services": "Services | Personalized Legal Services",
        "page_title_about": "About Us | Personalized Legal Services",
        "page_title_prices": "Prices | Personalized Legal Services",
        "logo": "Legal Company",
        "nav_home": "Home",
        "nav_about": "About Us",
        "nav_services": "Services",
        "nav_prices": "Prices",
        "nav_blog": "Blog",
        "nav_contact": "Contact",
        "nav_login": "Dashboard",
        "theme_toggle": "Light Theme",
        "language_toggle_ru": "RU",
        "language_toggle_en": "EN",
        "about_title": "About our company",
        "services_title": "Our services",
        "about_description": "Our law firm has many years of experience in providing high-quality legal services to corporate clients. We strive to provide our clients with personalized solutions that meet their unique needs.",
        "hero_title": "Personalized Legal Services",
        "hero_subtitle": "We provide high-quality legal solutions tailored to your needs.",
        "hero_button": "Our Services",
        "about_section_title": "About Our Company",
        "about_section_description": "Our legal company was founded in 2010 with the aim of providing high-quality legal services to corporate clients. Over the years, we have established ourselves as a reliable partner offering individualized solutions for each client.",
        "mission_title": "Our Mission",
        "mission_description": "We strive to provide our clients with expert legal support, facilitating the successful development of their businesses and the protection of their interests. Our mission is to be leaders in corporate law, offering innovative and effective solutions.",
        "team_title": "Our Team",
        "team_member1_alt": "Ivan Ivanov",
        "team_member1_name": "Ivan Ivanov",
        "team_member1_position": "General Director",
        "team_member2_alt": "Maria Petrova",
        "team_member2_name": "Maria Petrova",
        "team_member2_position": "Chief Legal Counsel",
        "team_member3_alt": "Alexey Smirnov",
        "team_member3_name": "Alexey Smirnov",
        "team_member3_position": "Client Relations Manager",
        "values_title": "Our Values",
        "value_professionalism": "Professionalism and Expertise",
        "value_individual_approach": "Individual Approach",
        "value_responsibility": "Responsibility and Reliability",
        "value_innovation": "Innovation and Development",
        "footer_text": "&copy; 2024 Legal Company. All rights reserved.",

        // Ключи для страницы услуг
        "services_section_title": "Our Services",
        "services_section_description": "We offer a wide range of legal services aimed at supporting and developing your business.",
        "service_corporate_consultations_title": "Corporate Law Consultations",
        "service_corporate_consultations_desc": "Professional consultations on corporate governance and structure issues.",
        "service_contracts_title": "Contract Development and Analysis",
        "service_contracts_desc": "Creation and review of legally sound contracts that protect your interests.",
        "service_litigation_title": "Court Representation",
        "service_litigation_desc": "Effective representation of your interests in court instances.",
        "service_tax_consulting_title": "Tax Consulting",
        "service_tax_consulting_desc": "Optimization of tax burden and compliance with all tax requirements.",

        // Ключи для страницы цен
        "pricing_section_title": "Our Prices",
        "pricing_section_description": "We offer transparent and competitive pricing policies tailored to each client's needs.",
        "pricing_card_basic": "Basic Plan",
        "pricing_plan_basic_title": "Basic",
        "pricing_plan_basic_price": "5,000",
        "pricing_plan_basic_currency": "₽/month",
        "pricing_plan_basic_feature1": "Consultations up to 2 hours",
        "pricing_plan_basic_feature2": "Development of standard contracts",
        "pricing_plan_basic_feature3": "Access to online resources",
        "pricing_plan_basic_button": "Choose",

        "pricing_card_standard": "Standard Plan",
        "pricing_plan_standard_title": "Standard",
        "pricing_plan_standard_price": "10,000",
        "pricing_plan_standard_currency": "₽/month",
        "pricing_plan_standard_feature1": "Consultations up to 5 hours",
        "pricing_plan_standard_feature2": "Development and analysis of contracts",
        "pricing_plan_standard_feature3": "Court representation",
        "pricing_plan_standard_feature4": "Tax consulting",
        "pricing_plan_standard_button": "Choose",

        "pricing_card_premium": "Premium Plan",
        "pricing_plan_premium_title": "Premium",
        "pricing_plan_premium_price": "20,000",
        "pricing_plan_premium_currency": "₽/month",
        "pricing_plan_premium_feature1": "Unlimited consultations",
        "pricing_plan_premium_feature2": "Comprehensive legal support",
        "pricing_plan_premium_feature3": "Individual business solutions",
        "pricing_plan_premium_feature4": "Priority support",
        "pricing_plan_premium_button": "Choose",

        // Секция Блога
        "blog_section_title": "Our Blog",
        "blog_section_description": "Read the latest articles, news, and tips from our legal service experts.",

        // Статьи
        "blog_post1_image_alt": "Article Title 1",
        "blog_post1_title": "Benefits of Using Legal Services for Your Business",
        "blog_post1_meta": "Author: Ivan Ivanov | Date: 20.04.2024 | Category: Corporate Law",
        "blog_post1_excerpt": "In today's business world, legal support plays a key role in ensuring the stability and growth of a company. In this article, we will explore the main benefits of using professional legal services...",
        "blog_post1_read_more": "Read More",

        "blog_post2_image_alt": "Article Title 2",
        "blog_post2_title": "How to Choose the Right Lawyer for Your Case",
        "blog_post2_meta": "Author: Maria Petrova | Date: 15.03.2024 | Category: Choosing a Lawyer",
        "blog_post2_excerpt": "Choosing a lawyer is an important step that can significantly impact the outcome of your case. In this article, we will share tips and recommendations to help you make the right choice...",
        "blog_post2_read_more": "Read More",

        "blog_post3_image_alt": "Article Title 3",
        "blog_post3_title": "New Changes in Tax Legislation for 2024",
        "blog_post3_meta": "Author: Alexey Smirnov | Date: 10.02.2024 | Category: Tax Law",
        "blog_post3_excerpt": "Each year, legislation undergoes changes, and tax law is no exception. In this article, we will examine the key changes in tax legislation that came into effect in 2024...",
        "blog_post3_read_more": "Read More",

        // Боковая панель (Sidebar)
        "sidebar_search_title": "Search",
        "sidebar_search_placeholder": "Search articles...",
        "sidebar_search_button": "Find",
        "sidebar_categories_title": "Categories",
        "sidebar_category_corporate": "Corporate Law",
        "sidebar_category_tax": "Tax Law",
        "sidebar_category_contracts": "Contract Law",
        "sidebar_category_labor": "Labor Law",
        "sidebar_category_international": "International Law",
        "sidebar_recent_posts_title": "Recent Posts",
        "sidebar_recent_post1_image_alt": "Recent Article 1",
        "sidebar_recent_post1_title": "Benefits of Using Legal Services for Your Business",
        "sidebar_recent_post2_image_alt": "Recent Article 2",
        "sidebar_recent_post2_title": "How to Choose the Right Lawyer for Your Case",
        "sidebar_recent_post3_image_alt": "Recent Article 3",
        "sidebar_recent_post3_title": "New Changes in Tax Legislation for 2024",
        "sidebar_archive_title": "Archive",
        "sidebar_archive_april": "April 2024",
        "sidebar_archive_march": "March 2024",
        "sidebar_archive_february": "February 2024",
        "sidebar_archive_january": "January 2024",

        "title": "Personalized Legal Services",
        "logo": "Legal Company",
        "nav_home": "Home",
        "nav_about": "About Us",
        "nav_services": "Services",
        "nav_prices": "Prices",
        "nav_blog": "Blog",
        "nav_contact": "Contact",
        "nav_login": "Dashboard",
        "theme_toggle": "Light Theme",
        "hero_title": "Personalized Legal Services",
        "hero_subtitle": "We provide high-quality legal solutions tailored to your needs.",
        "hero_button": "Our Services",
        "about_title": "About Our Company",
        "about_description": "Our legal company has many years of experience in providing high-quality legal services to corporate clients. We strive to provide our clients with personalized solutions that meet their unique needs.",
        "services_title": "Our Services",
        "service_consultations": "Consultations",
        "service_consultations_desc": "Professional legal consultations on various matters.",
        "service_contracts": "Contract Law",
        "service_contracts_desc": "Development and analysis of contracts, protecting your interests.",
        "service_litigation": "Court Representation",
        "service_litigation_desc": "Effective representation of your interests in court instances.",
        "service_corporate": "Corporate Law",
        "service_corporate_desc": "Legal support for business at all stages.",
        "advantages_title": "Why Choose Us",
        "advantage_experienced": "Experienced team of professionals",
        "advantage_individual": "Individual approach to each client",
        "advantage_responsibility": "High level of responsibility and ethics",
        "advantage_comprehensive": "Comprehensive business solutions",
        "footer_text": "&copy; 2024 Legal Company. All rights reserved."
    }
};

// Текущий язык
let currentLanguage = localStorage.getItem('language') || 'ru';

// Функция для перевода элементов
function translatePage(lang) {
    const elements = document.querySelectorAll('[data-i18n]');
    elements.forEach(element => {
        const key = element.getAttribute('data-i18n');
        if (translations[lang] && translations[lang][key]) {
            // Специальный случай для тега <title>
            if (element.tagName.toLowerCase() === 'title') {
                document.title = translations[lang][key];
            }
            // Перевод атрибута alt
            else if (element.hasAttribute('alt') && !element.hasAttribute('data-i18n-alt')) {
                element.setAttribute('alt', translations[lang][key]);
            }
            // Перевод атрибута placeholder (если необходимо)
            else if (element.hasAttribute('placeholder')) {
                element.setAttribute('placeholder', translations[lang][key]);
            }
            // Перевод текстового содержимого
            else {
                element.innerHTML = translations[lang][key];
            }
        }
    });

    // Обновление текста кнопки переключения темы
    const themeToggleBtn = document.getElementById('themeToggle');
    if (themeToggleBtn) {
        themeToggleBtn.innerHTML = translations[lang]['theme_toggle'];
    }

    // Обновление текста кнопки переключения языка
    const languageToggleBtn = document.getElementById('languageToggle');
    if (languageToggleBtn) {
        languageToggleBtn.innerHTML = lang === 'ru' ? translations[lang]['language_toggle_en'] : translations[lang]['language_toggle_ru'];
    }

    // Обновление атрибута lang у тега <html>
    document.documentElement.setAttribute('lang', lang);

    // Сохранение текущего языка в localStorage
    localStorage.setItem('language', lang);
}

// Инициализация перевода при загрузке страницы
document.addEventListener('DOMContentLoaded', () => {
    translatePage(currentLanguage);

    // Обработчик клика по кнопке переключения языка
    const languageToggleBtn = document.getElementById('languageToggle');
    if (languageToggleBtn) {
        languageToggleBtn.addEventListener('click', () => {
            currentLanguage = currentLanguage === 'ru' ? 'en' : 'ru';
            translatePage(currentLanguage);
        });
    }
});
